POST 127.0.0.1:8080/get
Content-Type: application/json

{
  "Document": {
    "id": 1
  }
}

###

POST 127.0.0.1:8080/get
Content-Type: application/json

{
  "document": {
    "name": "TommyLemon"
  }
}

###

POST 127.0.0.1:8080/get
Content-Type: application/json

{
  "User[]": {
    "User": {
      "id{}":[38710,82001,70793]
    }
  }
}

###

POST 127.0.0.1:8080/get
Content-Type: application/json

{
  "User[]": {
    "User": {
      "id{}": "<38711"
    }
  }
}

###

POST 127.0.0.1:8080/get
Content-Type: application/json

{
  "User[]": {
    "User": {
      "id{}": ">70793,"
    }
  }
}


### 添加一条记录

POST 127.0.0.1:8080/post
Content-Type: application/json

{
  "Comment":{
    "id": 116136422088499,
    "userId": 82012,
    "momentId":12,
    "content":"APIJSON,let interfaces and documents go to hell !"
  },
  "tag":"Comment"
}

### 更新一条记录

POST 127.0.0.1:8080/put
Content-Type: application/json

{
  "Comment":{
    "id": 301,
    "content":"put is ok",
    "toId": 97
  },
  "tag":"Comment"
}